server:
  port: 80
logging:
  level:
    root: info
  file: /data/wecard/log/wecard.log

upload:
  path: /data/wecard/upload

spring:
  datasource:
    name: primary
    url: jdbc:mysql://cdb-nvpvbikk.bj.tencentcdb.com:10146/wecard?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xuTong123+
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20